{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gameify",
    "module": "Gameify",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Gameify-1.0-SNAPSHOT.jar",
          "url": "Gameify-1.0-SNAPSHOT.jar",
          "size": 7683,
          "sha512": "079119ee0a9f797d849cb5b81174d7554516b09dece7b371d0faa50b414750ede5c35a57fd0a016a04dc33dd5a8f3945ffa65c5f7eb3c4cb674e872172db2be5",
          "sha256": "ae117f764a02e639b33ec50da67910a0825617812de30311f915616b08095c59",
          "sha1": "f38f0df40ba4111907c2e591810b79dd70038270",
          "md5": "9d5c6782e7869982a96a5ef468e53e4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Gameify-1.0-SNAPSHOT.jar",
          "url": "Gameify-1.0-SNAPSHOT.jar",
          "size": 7683,
          "sha512": "079119ee0a9f797d849cb5b81174d7554516b09dece7b371d0faa50b414750ede5c35a57fd0a016a04dc33dd5a8f3945ffa65c5f7eb3c4cb674e872172db2be5",
          "sha256": "ae117f764a02e639b33ec50da67910a0825617812de30311f915616b08095c59",
          "sha1": "f38f0df40ba4111907c2e591810b79dd70038270",
          "md5": "9d5c6782e7869982a96a5ef468e53e4b"
        }
      ]
    }
  ]
}
