{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gameify",
    "module": "gameify",
    "version": "1.1.0-24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gameify-1.1.0-24.jar",
          "url": "gameify-1.1.0-24.jar",
          "size": 15194,
          "sha512": "2adea0a2b83476ca2af7c689999c14b89148d0f2a1cf73982ba3fe7718f1b23091a275f597943351bf69a77aef06f0ba8d7c8422d5fc4c5547f75473a8c18133",
          "sha256": "29f0115372aabdd2d2cf28cb7165ad1de2d062afa5946e867cba3095fcf3c896",
          "sha1": "3690482e48612f7b21d1ad3d3672d4d33f6bb5f7",
          "md5": "c2faffacc16b423491397d150af34a4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gameify-1.1.0-24.jar",
          "url": "gameify-1.1.0-24.jar",
          "size": 15194,
          "sha512": "2adea0a2b83476ca2af7c689999c14b89148d0f2a1cf73982ba3fe7718f1b23091a275f597943351bf69a77aef06f0ba8d7c8422d5fc4c5547f75473a8c18133",
          "sha256": "29f0115372aabdd2d2cf28cb7165ad1de2d062afa5946e867cba3095fcf3c896",
          "sha1": "3690482e48612f7b21d1ad3d3672d4d33f6bb5f7",
          "md5": "c2faffacc16b423491397d150af34a4c"
        }
      ]
    }
  ]
}
